// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8S7FQMeMbqj10-Z0_9xUoe-7jTcZ63CA',
    appId: '1:137235369956:android:a25944de87d141c74f41f1',
    messagingSenderId: '137235369956',
    projectId: 'speech-world-003',
    storageBucket: 'speech-world-003.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPxbnl3cF6llTw1xnSzr7yydOWdpG-CVk',
    appId: '1:137235369956:web:85f0087752a50cf84f41f1',
    messagingSenderId: '137235369956',
    projectId: 'speech-world-003',
    authDomain: 'speech-world-003.firebaseapp.com',
    storageBucket: 'speech-world-003.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV677IpEo1o55pkcvvOY1IwaQff56xy-Y',
    appId: '1:137235369956:ios:dc0e0ff4ce5d977d4f41f1',
    messagingSenderId: '137235369956',
    projectId: 'speech-world-003',
    storageBucket: 'speech-world-003.firebasestorage.app',
    androidClientId: '137235369956-7rvuar9gnt999712arcs1qgac39kani6.apps.googleusercontent.com',
    iosClientId: '137235369956-12p1v49j58an1hbkeg3j05qo3flvgnf1.apps.googleusercontent.com',
    iosBundleId: 'com.example.speechWorld',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV677IpEo1o55pkcvvOY1IwaQff56xy-Y',
    appId: '1:137235369956:ios:dc0e0ff4ce5d977d4f41f1',
    messagingSenderId: '137235369956',
    projectId: 'speech-world-003',
    storageBucket: 'speech-world-003.firebasestorage.app',
    androidClientId: '137235369956-7rvuar9gnt999712arcs1qgac39kani6.apps.googleusercontent.com',
    iosClientId: '137235369956-12p1v49j58an1hbkeg3j05qo3flvgnf1.apps.googleusercontent.com',
    iosBundleId: 'com.example.speechWorld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPxbnl3cF6llTw1xnSzr7yydOWdpG-CVk',
    appId: '1:137235369956:web:7f41b69b5be52a634f41f1',
    messagingSenderId: '137235369956',
    projectId: 'speech-world-003',
    authDomain: 'speech-world-003.firebaseapp.com',
    storageBucket: 'speech-world-003.firebasestorage.app',
  );

}